Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -29,19 +29,21 @@ jobs:
           curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
           chmod a+x ~/bin/repo
 
-      - name: Синхронизация PixelOS (sixteen-qpr2)
+      - name: Синхронизация PixelOS
         run: |
           export PATH=~/bin:$PATH
           mkdir -p ~/android && cd ~/android
           repo init -u https://github.com/PixelOS-AOSP/android_manifest.git -b sixteen-qpr2 --git-lfs --depth=1
           repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune
 
-      - name: Клонирование дерева устройства, ядра и вендора
+      - name: Клонирование исходников устройства
         run: |
           cd ~/android
           git clone https://github.com/LineageOS/android_device_xiaomi_mondrian.git -b lineage-23.2 device/xiaomi/mondrian
-          git clone https://github.com/LineageOS/android_kernel_xiaomi_sm8475.git -b lineage-23.2 kernel/xiaomi/sm8475
-          git clone https://github.com/TheMuppets/proprietary_vendor_xiaomi.git -b lineage-23.2 vendor/xiaomi
+          git clone https://github.com/LineageOS/android_kernel_xiaomi_sm8450.git -b lineage-23.2 kernel/xiaomi/sm8450
+          git clone https://github.com/LineageOS/android_kernel_xiaomi_sm8450-modules.git -b lineage-23.2 kernel/xiaomi/sm8450-modules
+          git clone https://github.com/TheMuppets/proprietary_vendor_xiaomi_mondrian.git -b lineage-23.2 vendor/xiaomi/mondrian
+          git clone https://github.com/TheMuppets/proprietary_vendor_xiaomi_sm8450-common.git -b lineage-23.2 vendor/xiaomi/sm8450-common
           git clone https://github.com/LineageOS/android_hardware_xiaomi.git -b lineage-23.2 hardware/xiaomi
 
       - name: Адаптация дерева под PixelOS
@@ -69,4 +71,4 @@ jobs:
 
       - name: Проверка результата
         run: |
-          ls -lh ~/android/out/target/product/mondrian/*.zip || echo "Сборка не завершена"
+          ls -lh ~/android/out/target/product/mondrian/*.zip || echo "Failed"
